### ISSUE TITLE
Call expressions as a shortcut for invoking functions

### ISSUE THREAD

**Issue by hinshun** [openllb/hlb#100]
In the beginning, I designed HLB to invoke functions without parenthesis or commas like so:

```hlb
fs default() {
    image "alpine"
    env "key" "value"
    run "echo $key > /out/foo" with option {
        mount fs { scratch; } "/out" as fooOut
    }
}
```

Compare this to invoking with parens:
```hlb
fs default() {
    image("alpine")
    env("key", "value")
    run("echo $key > /out/foo") with option {
        mount fs { scratch(); } "/out" as fooOut
    }
}
```

It's a bit verbose and doesn't have the same readability as Dockerfiles so we ended up with what we have now. However, there are some common patterns that emerged:

### Running with string interpolated values
```hlb
run string {
    format "npm run %s" script
} with option {
    ...
}
```

### Mounting local and scratch filesystems
```hlb
run "go build -o /out/binary ./cmd/my-binary" with option {
    dir "/src"
    mount fs { local "."; } "/src"
    mount fs { scratch; } "/out"
}
```

### Proxying environment variables
```
option::run awsCredentials() {
    proxyEnv "AWS_ACCESS_KEY_ID"
    proxyEnv "AWS_SECRET_ACCESS_KEY"
    proxyEnv "AWS_SESSION_TOKEN"
}

option::run proxyEnv(string key) {
    env key string { localEnv key; }
}
```

Having to create a `fs { ... }` or `string { ... }` just to invoke one function is often too verbose. It only makes sense if you want to modify something so you end up having multiple statements:

```
run "make" with option {
    dir "/src"
    mount fs {
        local "."
        rm "./git/objects"
        mkdir "node_modules" 0o755
    } "/src"
}
```

I propose we support parens-style invocation of functions as an alternative, in order to reduce verbosity in these examples:

### Running with string interpolated values
```hlb
run format("npm run %s", script) with option {
    ...
}
```

### Mounting local and scratch filesystems
```hlb
run "go build -o /out/binary ./cmd/my-binary" with option {
    dir "/src"
    mount local(".") "/src"
    mount scratch "/out"
}
```

### Proxying environment variables
```
option::run awsCredentials() {
    proxyEnv "AWS_ACCESS_KEY_ID"
    proxyEnv "AWS_SECRET_ACCESS_KEY"
    proxyEnv "AWS_SESSION_TOKEN"
}

option::run proxyEnv(string key) {
    env key localEnv(key)
}
```

**Comment by coryb** [comment]
I am generally for this proposal.  I would prefer the argument list syntax to be consistent though re commas.  Currently commas are only used for the declaration, not the invocation, ie:
```
string hi(string first, string last) {
  format "Hi %s %s" first last
}
```
It does not make sense to me to have commas in one invocation but not the other, ie this does not make sense to me:
```
hi(first, last)
```
vs
```
string {
  hi first last
}
```
So I think the commas are not necessary on the invocation with parens:
```
hi(first last)
```
