### ISSUE TITLE
no syntax error when using imported group in fs block

### ISSUE THREAD

**Issue by coryb** [openllb/hlb#151]
When using a `group` in an `fs` we get an error when the `group` is locally defined:
```
fs default() {
	grp
}

group grp() {
	parallel fs {
		image "busybox"
		run "echo hi"
	}
}
```
Expected error:
```
$ ./hlb run ./test.hlb
./test.hlb:2:2: expected arg to be type fs, found group
```
However when we use an imported group, there is no warning, and the build graph is a no-op, which is super confusing.

```
import go from fs {
	image "openllb/go.hlb"
}

fs default() {
	go.buildUnix fs {
		local "."
	} "github.com/openllb/hlb/cmd/hlb"
}
```
Here is the `--tree` output:
```
$ ./hlb run --tree ./test.hlb
[+] Building 1.9s (2/2) FINISHED
 => CACHED [import go] docker-image://docker.io/openllb/go.hlb:latest  0.0s
 => => resolve docker.io/openllb/go.hlb:latest                         1.3s
 => compiling [default]                                                1.8s
.
```

**Comment by hinshun** [comment]
Not sure when exactly this was fixed, but this is how it looks in: https://github.com/openllb/hlb/pull/191
![cannot-group-as-fs](https://user-images.githubusercontent.com/6493975/98482701-f9e1f900-21b7-11eb-8453-093bba8d4af5.png)
