### ISSUE TITLE
should we trim `localRun` output automatically

### ISSUE THREAD

**Issue by coryb** [openllb/hlb#153]
For our hlb build we need to embed the local version in our go binary, I currently have something like this:
```
string version() {
	localRun "git describe --match 'v[0-9]*' --tags --dirty='.dirty' --always | sed 's/^v//'"
}
```
which returns something like:
```
0.0.16-8072-gaee928515.dirty\n
```

Since the `git describe` command prints a newline we end up capturing that in the value.  I can hack it by adding `| xargs echo -n` at the end, but that is a gross hack.  I wonder if we should implicitly trim the trailing newline similar to how bash does with capturing output like:
```
x=$(git describe)
```
In that case `x` will not have the trailing newline.

I expect this will be the common expectation, but maybe we can add some `localRun` options to change this behavior.

So I am thinking this returns the result with trailing newline trimmed:
```
localRun "echo hi"
```
and maybe something like this to return raw output with no trimming:
```
localRun "echo hi" with raw
```

Thoughts?

**Comment by hinshun** [comment]
Hi @coryb, does `raw` ever add anything except the newline? If not, I think we can just always trim the newline, since users can just add a `\n` using `format`.

**Comment by coryb** [comment]
I was thinking `raw` would be used to return unprocessed output, exactly as the command output (so no trimming with `raw`).  We can skip `raw` for now since I am not entirely sure there is a need.

It seems the bash behavior is to trim all trailing newlines:
```
$ x=$(echo -e "\n\nfoo\n\n")
$ printf -- "-->%s<--" "$x"
-->

foo<--
```

It will not trim trailing whitespace:
```
$ x=$(echo -e "\n\nfoo\n \n")
$ printf -- "-->%s<--" "$x"
-->

foo
 <--
```
```
$ x=$(echo -e "   foo   ")
$ printf -- "-->%s<--" "$x"
-->   foo   <--
```
