### ISSUE TITLE
Expose function side effects for aliases

### ISSUE THREAD

**Issue by slushie** [openllb/hlb#163]
## Context

HLB programs provide operations over implicit state variables. Concretely, within a user-defined function `fs default()`, every statement in the function block takes as input a state of type `fs` and produces the (optionally modified) state as output. No statements may change the type of the state. 

Because no statements may change the type of the state, some statements have modifiers which introduce new _dependent_ state. The `with option` modifier to a `run` statement creates a new state of type `option::run` that is used as input by all statements in the block. The `option::run` state is dependent on the `fs` state of the enclosing `run` statement and any `option::run` statement can access the enclosing `fs` state.

Rather than modify the state in-place, statements perform monadic operations over the state value. State therefore may be expressed in terms of a _chain_ (or pipeline, or stack) of function calls over the state value. For example, `default(state) :: dockerPush(run(image(state)))`. Each function call in the chain may produce _side effects_ of any type but must always return a value of the proper type.

## Problem statement

For most usages, the `as` keyword provides an _alias_ to a particular monadic value along the chain. For exactly one usage (the `mount` function), the `as` keyword provides an alias to a side effect on the state. No language feature provides access to side effects of other monadic operations. 

We want consistent syntax for accessing side effects of functions. We want to add consistency in the use of aliases on `mount` in line with the rest of the language. 

## Proposal

Extend the language to expose side effects explicitly. Call statements may include a modifier to access the side effects of the operation by their name, using the `as` keyword to create a typed alias pointing to their value.

This allows for type-safe extensibility and leaves most semantics unchanged. When used to modify a call statement, `as` would create an alias pointing to the state value after the operation. When used in a `var` block, `as` would create an alias pointing to the named side effect. For convenience, when used to modify a call statement with an inline `effect`, `as` would create an alias pointing to the first side effect defined.

For example,

```
run "head -c 10 /dev/random > /out/rnd" with option {
    mount src "/out" effect as aliasA
} effects var {
    int exitCode as aliasB
} as aliasC
```

In this case, `aliasA` points to the first side effect of `mount`; `aliasB` points to the side effect named "exitCode"; `aliasC` points to the state value returned by "run".

The trouble here is that we must disambiguate between aliases pointing to the side effects and those pointing to the state value. In this example, we add the `effects` keyword before aliases pointing to side effects. Unfortunately, this is a breaking change in the language. But it enables syntax like `mount src path effects as sideEffectAlias as runOptionAlias` where `runOptionAlias` has type `option::run` and `sideEffectAlias` has type `fs`.

It also requires new syntax on function declarations to expose the named side effects. For example,

```
option::run mount(fs src, string path) effects var {
    fs target
}
```

Where `fs target` exposes an fs side effect which can be consumed as above.

### Encoding state dependency

Taking this logically further, it may be desirable to consider the dependent `option::run` type as `option::run<fs>` and thus, the return value of `mount` can wrap its `fs target` in the `option::run` type. In other words, `mount` returns `option:::run<fs target>` and `mount src path as aliasD` and `aliasD` points to `fs target`, an independent state value. 

This requires no changes to the language for alias consumers. But it does require changes to the type system to allow parameterized types. This encodes state dependencies explicitly, so may be a worthwhile goal beyond its use in this proposal.

## Alternate proposal: Multiple return values

Extend the language to let functions define multiple return values. One of these must be the same type as the current state, but the others may be any type. Those values would be accessed via the `as` keyword. For example,

```
dockerPush "some/ref:latest" as id
```

The `dockerPush` function returns `(fs, string)` and the `as` keyword creates an _alias_ that points to `string`. The `fs` return value is used as the next monadic state value in the chain. 

When only one return value is provided, it must be used both for the state and the alias. Functions that return more values might be aliased multiple times, in order. For example, if `dockerPush` returns `(fs, string, int)` it might be used as in:

```
dockerPush "some/ref:latest" as id, size
```

This solution is simpler to implement but it may be confusing to readers. It also leaves ambiguity when consuming less than all defined return values. It does not provide syntax to alias the state value if another return value is provided.

**Comment by hinshun** [comment]
@slushie This is well written, thank you for this. :+1:

## Proposal

> ```
> run "head -c 10 /dev/random > /out/rnd" with option {
>     mount src "/out" effect as aliasA
> } effects var {
>     int exitCode as aliasB
> } as aliasC
> ```
> 
> In this case, `aliasA` points to the first side effect of `mount`; `aliasB` points to the side effect named "exitCode"; `aliasC` points to the state value returned by "run".

I see why you needed a new block type here because option functions return options. However, the `int` type of `exitCode` seems like boilerplate because it must only be `int`. If we strip away the duplicate typing of `exitCode` it looks very similar to options.

```
run "head -c 10 /dev/random > /out/rnd" with option {
    mount src "/out" as aliasA
    exitCode as aliasB
} as aliasC
```

> The trouble here is that we must disambiguate between aliases pointing to the side effects and those pointing to the state value. In this example, we add the `effects` keyword before aliases pointing to side effects. Unfortunately, this is a breaking change in the language. But it enables syntax like `mount src path effects as sideEffectAlias as runOptionAlias` where `runOptionAlias` has type `option::run` and `sideEffectAlias` has type `fs`.
> 
> It also requires new syntax on function declarations to expose the named side effects. For example,
> 
> ```
> option::run mount(fs src, string path) effects var {
>     fs target
> }
> ```
> 
> Where `fs target` exposes an fs side effect which can be consumed as above.
> 
> ### Encoding state dependency
> Taking this logically further, it may be desirable to consider the dependent `option::run` type as `option::run<fs>` and thus, the return value of `mount` can wrap its `fs target` in the `option::run` type. In other words, `mount` returns `option:::run<fs target>` and `mount src path as aliasD` and `aliasD` points to `fs target`, an independent state value.
> 
> This requires no changes to the language for alias consumers. But it does require changes to the type system to allow parameterized types. This encodes state dependencies explicitly, so may be a worthwhile goal beyond its use in this proposal.

## Alternate proposal: Multiple return values

> Extend the language to let functions define multiple return values. One of these must be the same type as the current state, but the others may be any type. Those values would be accessed via the `as` keyword. For example,
> 
> ```
> dockerPush "some/ref:latest" as id
> ```
> 
> The `dockerPush` function returns `(fs, string)` and the `as` keyword creates an _alias_ that points to `string`. The `fs` return value is used as the next monadic state value in the chain.
> 
> When only one return value is provided, it must be used both for the state and the alias. Functions that return more values might be aliased multiple times, in order. For example, if `dockerPush` returns `(fs, string, int)` it might be used as in:
> 
> ```
> dockerPush "some/ref:latest" as id, size
> ```
> 
> This solution is simpler to implement but it may be confusing to readers. It also leaves ambiguity when consuming less than all defined return values. It does not provide syntax to alias the state value if another return value is provided.

**Comment by slushie** [comment]
> I see why you needed a new block type here because option functions return options. However, the `int` type of `exitCode` seems like boilerplate because it must only be `int`. If we strip away the duplicate typing of `exitCode` it looks very similar to options.
> 
> ```
> run "head -c 10 /dev/random > /out/rnd" with option {
>     mount src "/out" as aliasA
>     exitCode as aliasB
> } as aliasC
> ```

It does indeed! But then `exitCode` would have to return `option::run` as well. We need some kind of syntax that is _non-monadic_ in order to access side effects.

The reason I like the type prefix is because it introduces a new syntax -- rather than a block with a list of `CallStmt`'s, we would have a list of some variant of `Decl`.  

> I'm wary of introducing `effects` and `vars`. Since `vars` is only used to expose side effects to be aliased, I don't think you can provide a function that returns `vars` because you won't be able to alias them there? (This is also a current problem with how aliases work today)

Yeah, this is an issue for user-defined functions that can't set values. IMHO the best solution is matching syntax. I played with this syntax earlier:

```
fs myFunc(string a) {
  set output string {
    format "input=%s" a
  }
} effects var {
  string output
}
```
> > Unfortunately, this is a breaking change in the language. But it enables syntax like `mount src path effects as sideEffectAlias as runOptionAlias` where `runOptionAlias` has type `option::run` and `sideEffectAlias` has type `fs`.
> 
> Many of existing HLB programs use alias without `effects`. Does this mean those will need to be migrated?

Yeah, I don't like breaking this but by providing access to side effects _and_ the state value, we need to differentiate in the syntax somehow. I think there are actually more current uses of `mount ... as ...` than `someFunc as ...`, so maybe it would be better to annotate _that_ syntax rather than the side effects.


> I think the signature is clear, but I wonder if we can have a more friendly term to replace `effects`. I think its correct and pure, but seems a bit off.

It's a terrible name :joy: I'm sure you can think of something that fits, but I'll try to think up some alternatives.

> > Encoding state dependency
> 
> Can you expand on this with examples? I'm not sure I follow.

This was actually the first solution I considered. Its a bit of a large hammer, though, because it breaks open the type system. Basically, by parameterizing types we can jam more values into the state and still make it count as the required type. 

That is, imagine `mount` return an `fs` wrapped in `option::run` -- call that type `option::run<fs>`. The alias then points to the composite type, which is an `fs` when you need it to be, and an `option::run` otherwise. In this way, `as` is "unwrapping" the monad value. 

Think of `as` like it were `store.GetOrElse("key", default)`. It would inspect the value, look for a composite value stored inside and return it, or else return the value itself. And `option::run` is not itself accessible via `as` because it is a wrapper for either something or nothing. 

Its hard to express this in HLB directly today, but here's some psuedo-code declarations:

```
# @return option::run an option for run
# @return option::run.fs an fs pointing to path
option::run <fs>  mount(fs src, string path) { ... }

# @return fs the current state
# @return fs.string the imageID
# @return fs.int the size of the image
fs <string, int> dockerPush(string ref)
```
and perhaps `as` is defined as:
```
as A<T?> :: if T then T else A
```
So `as` is like a loosely-typed equivalent of Haskell's `bind`. I can imagine this behaviour used for other monadic operations as well, for example a `not` could be defined as `not A<T?> :: if T then A else fail`. And perhaps that's _really_ what the `effects var` syntax I proposed is really doing. So its a pretty powerful pattern, but would require a lot of work in the HLB type system.

> ## Alternate proposal: Multiple return values
> 
> I do like this idea. So would the signature for `mount` look something like?
> 
> ```
> (option::run, fs) mount(fs input, string mountpoint)
> ```
> 
> Looks kind of like golang. 

Yeah it does, and golang's syntax is somewhat unique. We could clean it up to look like `option::run mount(fs in, string path) as fs` where the `FuncDecl.Types` is an array and `option::run` is element 0.


> Perhaps you can also do this:
> 
> ```
> dockerPush "some/ref:latest" as (_, size)
> ```

:+1:

> 
> > It does not provide syntax to alias the state value if another return value is provided.
> 
> What do you mean by this?

I only mean that we're saying `as` is for referencing return values _after_ the first. So while you could do `dockerPush "x" as id` to get the second value (a string), you couldn't get the first value (an fs).

**Comment by slushie** [comment]
After discussion, we agreed to implement the following syntax:

```
# side effects are defined via a clause on the function declaration
# they become part of the functions signature and can be type-checked
fs dockerPush(string ref) as (string imageID, int size)

fs foo(fs src) {
    run "cmd" with option {
        # bind "myTarget" to side effect named "source"
        mount src "/" with readonly as (source myTarget) 
        # bind "myTarget" to the first declared side effect
        # we'll keep this syntax for backward compatibility and convenience
        mount src "/" with readonly as myTarget
    }
}
```

**Comment by slushie** [comment]
Closing now that PR #164 is merged.
