### ISSUE TITLE
Defining outputs in HLB rather than in command-line

### ISSUE THREAD

**Issue by hinshun** [openllb/hlb#18]
When we land multi-targets in #47, it is only helpful if we can output the targets to different locations.

1. Output as soon as targets have been solved, without waiting for other parts of the graph
2. Multiple outputs per target, useful when wanting to push to multiple registries

Proposal
---

## HLB CLI

We'll move away from `hlb run --download <dest> ` / `hlb run --push <ref>` and instead bring it down into `hlb` functions.

But you'll still be able to specify output flags on the command line:
- `hlb run --target foo,download=.`

The target is splitted on the sentinel `,` and the first value is always the target name, followed by key values for output flags.

## Builtin Functions
```hlb
# Outputs the filesystem to external sources. If no options are
# defined, this is a no-op.
#
# @return the filesystem unchanged.
fs (fs) output()

# Pushes the filesystem to a registry following the distribution
# spec: https://github.com/opencontainers/distribution-spec/
#
# @param ref a docker registry reference. if not fully qualified, it will be
# expanded the same as the docker CLI.
# @return an option to push the filesystem to a registry.
option::output push(string ref)

# Downloads the filesystem to a local path.
#
# @param localPath the destination filepath for the filesystem contents.
# @return an option to download a filesystem to the local system.
option::output download(string localPath)

fs default() {
    scratch
    mkfile "/out" 0o644 "hello world"
    output with option {
        push "us-east-1.registry/foo:latest"
        push "us-west-2.registry/foo:latest"
    }
}
```

By running the `default` target, we end up solving the graph and pushing it to two different registries.

**Note this changes HLB from a compiler to more of an interpreter, unless BuildKit supports these output vertices in LLB**

## Outputs happen concurrently with rest of graph

Output returns the same `input` filesystem so you can continue chaining statements afterwards:
```hlb
fs default() {
    scratch
    mkfile "/out" 0o644 "hello world"
    output with option {
        push "foo:latest"
    }
    env "key" "value"
}
```

**Comment by slushie** [comment]
What does `string fooRef()` return exactly? The same tag you've pushed, or the registry's resolved digest? What about the `download` option, what does its alias return? 

Could `download` be used with a path, to choose a specific path (or paths) from an fs to download locally?

Also, I'm not sure I understand why `output` is used inside of a `fs`. Is that just to get the return value of the `output`'s fs as the return value of `foo`? Would it be valid to use `output` to modify an fs state? eg,
```
fs myOutput {
  image "alpine"
  run "apk add foopkg" as foopkg
  output fs {
     scratch
     copy foopkg "/usr/bin/foo" "/foo"
  }
}
```

**Comment by hinshun** [comment]
Hi @slushie 

> What does `string fooRef()` return exactly? The same tag you've pushed, or the registry's resolved digest? What about the `download` option, what does its alias return?
> 
> Could `download` be used with a path, to choose a specific path (or paths) from an fs to download locally?

After thinking about it some more, I don't think it makes sense to implement `Blocking statement to wait for output (like push) to complete`. In BuildKit, the following exporters are available:

```go
	ExporterImage  = "image"
	ExporterLocal  = "local"
	ExporterTar    = "tar"
	ExporterOCI    = "oci"
	ExporterDocker = "docker"
```

And of those, the exporters `local`, `tar`, `oci`, and `docker` all come in the form of a local file transfer (via rsync-style, or a tarball). Waiting for local downloads to complete isn't something I see as a usecase in BuildKit because you'd have to transfer it back in order to use it. You might as well depend on the vertex directly without the local round-trip.

As for `image`, you may want to wait for push to complete before building a Dockerfile that depends on it, but I think push can potentially be implemented in a frontend (solve an input graph, extract out rootsf, generate image config, push to registry), so we could depend on it like any other LLB vertex.

> Also, I'm not sure I understand why `output` is used inside of a `fs`. Is that just to get the return value of the `output`'s fs as the return value of `foo`?

Yes, the `output <fs input>` is a no-op because it returns the `fs input` unchanged. After mulling over this, I think why it'll be useful is that you may want to `output` a graph during the execution of a graph, rather than having it as a separate leaf node you target. If we were to pull it out as a new type of declaration:

```hlb
# style 1
output fooOutput() {
    foo # start from fs source stmt? doesn't make too much sense
    push "foo:latest"
}

# style 2
output foo as fooOutput with option { # option block? or new type exporter block?
   push "foo:latest"
}

fs foo {
    # ...
}
```

It feels a little counter intuitive to target `fooOutput` rather than `foo` just so that you can get an `output` target. You may never end up using the `foo` identifier so it seems pretty redundant there.

In any proposal to `output` a filesystem, you need to specify the following:
1. A keyword to represent that you want to do an output operation
2. An identifier in order to target it (in the current proposal as a `fs output()` function, the target is the parent function)
3. A block containing export options (be it `option { ... }` or `exporter { ... }` etc.)

I wonder if there's a better way to declare them?

> Would it be valid to use `output` to modify an fs state? eg,
> 
> ```
> fs myOutput {
>   image "alpine"
>   run "apk add foopkg" as foopkg
>   output fs {
>      scratch
>      copy foopkg "/usr/bin/foo" "/foo"
>   }
> }
> ```

No I don't believe it would be valid since `output` is a method not a function. Consider the following function:

```hlb
fs default() {
    image "alpine"
    image "busybox"
}
```

If implemented, `image "alpine"` is a no-op because it cannot be used since the base is now `busybox`.

Perhaps we also define a method `fs (fs) output() {}` so you can do something like:
```hlb
fs foobar {
  image "alpine"
  run "apk add foopkg" as foopkg
}

fs myOutput {
  foopkg
  output with option { push "foopkg:latest"; }
}
```

Though I think that's more a preference than anything.
