### ISSUE TITLE
String interpolation of environment variables

### ISSUE THREAD

**Issue by quidryan** [openllb/hlb#2]
It would be nice to have environment variable substitution in Strings, especially in `local`. Environment variables are commonly used to put strings together or reference where files are on the local filesystem, like `$HOME`.

In this example, is impossible to generalize for different users without environment variables:

```
fs homeConfiguration() {
  local "/home/quidryan/.myconfig"
}
```

The used environment variables would probably have to be considered part of the input for caching.

**Comment by hinshun** [comment]
We already do have string substitution like so:
```hlb
fs example(string package) {
    image "node:alpine"
    run string { format "npm install %s" package; }
}
```

We can add a builtin function `getEnv` for strings, so you could do this:
```hlb
fs homeConfiguration() {
    local string {
        format "%s/.myconfig" string { getEnv "HOME"; }
    }
}
```

That said, I think we should support paths starting with `~`, so this particular example should be simpler. What do you think?
