### ISSUE TITLE
Should aliases be part of the function signature?

### ISSUE THREAD

**Issue by copperlight** [openllb/hlb#227]
In HLB, aliases can be defined anywhere, yet they have the same importance and properties as functions, given that they inherit the signature of their enclosing function. In practice, it appears that when a function has an alias defined, it is no longer accessed by its name and its alias becomes the primary entry point, so that you can access a filesystem side effect. This makes for an awkward code reading experience.

In many programming languages, important concepts, such as imports and function definitions, are anchored to the upper left of your screen, or belong on their own line, separate from what follows them. This makes it easy to visually scan for these items and parse them, which helps readers form a mental model of the code.

With the ability to define aliases anywhere, they could be nested several levels deep and far off to the lower right side of whatever code block they belong to. As a result, they tend to be one of the last things noticed in a function, yet there may be more than one reference to them as an export or in other function calls. Defining aliases deep within functions also places them farther away from the function signature they inherit, so you may need to scan back and forth between them.

Example code from the tutorial:

```
fs npmInstall() {
    image "node:alpine"
    run "apk add -U git"
    run "git clone https://github.com/left-pad/left-pad.git /src"
    dir "/src"
    run "npm install" with option {
        mount fs { scratch; } "/src/node_modules" as nodeModules
    }
}
```

Example code from the managed artifacts workshop:

```
export extracted

# Fetches and verifies the nodejs tarball from nodejs.org and then extracts
# it into a scratch mount.
#
# @param version the version of nodejs.
# @return a leftover filesystem. do not use.
fs fetch(string version) {
	image "alpine"
	run "apk add -U gnupg"

	# Trust the GPG release keys of nodejs.org.
	run <<~GPG
                set -ex &&
                for key in
                        ...
                ; do
                        gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key" ||
                        gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys "$key" ||
                        gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ;
                done
	GPG

	# Verify the nodejs tarball using the detached GPG signature.
	run "gpg --verify /in/node.tar.gz.asc" with option {
		mount fs {
			scratch
			copy fs { tarball version; } "/" "/"
			copy fs { asc version; } "/" "/"
		} "/in" with readonly
	}
	mkdir "/out" 0o775

	# Extract the tarball into a scratch mount.
	run <<~TAR
		tar -xzf /in/node.tar.gz -C /out/ --strip-components=1 --no-same-owner &&
		cd /out/bin && ln -s ./node ./nodejs
	TAR with option {
		mount fs {
			tarball version
		} "/in" with readonly

		# A filesystem containing a nodejs installation. This should be extracted
		# into `/usr/local`.
		#
		# @return a filesystem containing a nodejs installation.
		mount scratch "/out" as extracted
	}
}
```

I am not sure how best to address this issue, but I have two ideas:

1. Add aliases to the function signature, to elevate the importance of this concept. This seems like it would be the simplest thing to do with the language in its current state. The downside to this approach is that you now have string duplication within the function, noting that the actual alias itself can be anywhere within the function.

```
fs npmInstall() alias nodeModules {
  ...
  ... as nodeModules
}

fs fetch(string version) alias extracted {
  ...
  ... as extracted
}
```

2. Replace aliases as a concept with custom return values. In the examples I have seen so far, any function with an alias defined ends up being accessed primarily though the alias and not the original function name. You could use a `return` keyword or similar to return the intermediate artifact, and this would make the function more transparent about the results that should be consumed.

**Comment by hinshun** [comment]
> Add aliases to the function signature, to elevate the importance of this concept. This seems like it would be the simplest thing to do with the language in its current state. The downside to this approach is that you now have string duplication within the function, noting that the actual alias itself can be anywhere within the function.

:+1: We actually have them in the function signature of builtins like so:
https://github.com/openllb/hlb/blob/a825e320f2f2e8e2373acf4130c975a7308543cc/language/builtin.hlb#L219

So for the same example it would look something like:
```
fs npmInstall() binds (fs nodeModules) {
  ...
  ... as nodeModules
}

fs fetch(string version) binds (fs extracted) {
  ...
  ... as extracted
}
```

The only reason we haven't done it yet is because it'll break backwards compatibility and we're still letting the idea brew a bit more. We could probably do some kind of deprecation + lint fix rule to make the transition more smooth if this is what we decide to pursue.

> Replace aliases as a concept with custom return values. In the examples I have seen so far, any function with an alias defined ends up being accessed primarily though the alias and not the original function name. You could use a return keyword or similar to return the intermediate artifact, and this would make the function more transparent about the results that should be consumed.

We can't do this because functions may have multiple aliases defined (e.g. one mount for output binary, one mount for cache directory).

**Comment by copperlight** [comment]
🤩 Wow, good discussion here! Multiple aliases had crossed my mind, but I had not seen any examples yet and I was not aware that they could have different return types.

I like the `binds` syntax - it makes clear the number of ways that you can access a function. Since you can have multiple aliases with different return types, this strongly suggests that allowing for a list of binds in the signature would be good. Using some sort of subscript notation to access function binds puts good emphasis on the original function name as the source.

The suggestion of dot notation here is reasonable - it makes the aliases feel a bit like "method" declarations within the function, but if the amount of change incurred in the code is high, maybe consider another character, such as `#` or `@`. The `#` symbol is used as an anchor in HTML and a method pointer in Javadocs, so I can see how it would be an anchor to a specific return type available from a function. The `@` is just a generic pointer character, but it can be used across many different contexts, such as hashes used in stakes.

I like the dot syntax for accessing imported functions - this feels natural. The double-colon syntax is also fine.

I like the angle brackets for subtypes better than the double-colon syntax - this feature reminds me more of generics.

```
########
# Current
########
import foo from "./foo.hlb"

fs default() {
    foo.build
       ^ dot syntax to access imported functions
}

option::run mount(fs input, string mountpoint) binds (fs target)
      ^^ double colon for subtypes
          
fs node() {
    ... as modules
}

fs other() {
    modules # call directly
}

#########
# Proposed
#########
import foo from "./foo.hlb"

fs default() {
    foo.build
       ^^ keep the dot notation to access imported functions
}

option<run> mount(fs input, string mountpoint) binds (fs target)
      ^^^^^ angle brackets for sub types (like generics)

fs node() binds (fs modules, string digest) {
          ^^^^^ type signature for additional return types
    ... as digest 
    ... as modules
}

fs other() {
    node#digest
    node#modules
        ^ hash syntax to access additional return values
}     
```

**Comment by hinshun** [comment]
Closing in favor of consolidating discussion in #248
