### ISSUE TITLE
"forward" option does not support multiple connections over TCP

### ISSUE THREAD

**Issue by slushie** [openllb/hlb#250]
There seems to be a bug in the current implementation of the `forward` option.  After the first connection, further connections forwarded from a TCP socket will timeout.

This is minimally reproducible by running a local listening socket on port 6000 (eg, `socat TCP-L:6000,reuseaddr,fork EXEC:hostname`) with the following HLB:

```hlb
fs default() {
  image "alpine"
  run "echo one | nc local:/socket && echo two | nc local:/socket" with option {
    forward "tcp://localhost:6000" "/socket"
  }
}
```

Investigating the problem, it looks like an issue in the `codegen.Forward.Call` func. For `tcp` and other non-`unix` protocols, the HLB client will spawn a goroutine to proxy connections to the buildkit client's Unix Domain socket. This socket is closed via a `WithCallback` solve option, but it is called very early and connections can be lost before the Solve completes.

I think it would be appropriate for the HLB client to maintain a single goroutine for all forwarding operations, so that they can be handled more robustly. It would attach to the _session_ rather than just a single vertex Solve. And could handle more complex use cases, like datagram sockets, proxies, and DNS.

**Comment by hinshun** [comment]
@coryb is this closed by https://github.com/openllb/hlb/pull/264? I know there is an additional suggestion here about managing all forwarding operations for the session together, but could be a separate issue.

**Comment by coryb** [comment]
Yeah, this was fixed, didnt realize there was an issue open.  Closing now.
