### ISSUE TITLE
platform confused when using multiple archs in same build graph

### ISSUE THREAD

**Issue by coryb** [openllb/hlb#278]
I would expect hlb to run:
```
fs default() {
	image "alpine" with platform("linux", "amd64")
	run "test $(uname -m) = x86_64" with option {
		mount fs {
			image "alpine" with platform("linux", "arm64")
			run "test $(uname -m) = aarch64" with ignoreCache
		} "/foobar" with readonly
	}
}
```
It currently doesnt, the inner `image` is having the amd64 platfrom applied from the parent scope and ignoring the platform argument.  So this graph ends up running amd64 for both vertexes.

**Comment by hinshun** [comment]
When marshalling llb, you have to specify constraints for platform otherwise you get default of `runtime.GOOS` and `runtime.GOARCH`. Either way, one platform is specified, and seems to override all child platform constraints. So this is a buildkit issue, not a hlb one.

**Comment by coryb** [comment]
We recently changed HLB to explictly set os/arch for all solves instead of allowing GOOS/GOARCH to be applied, I suspect the bug is there.
