### ISSUE TITLE
ModuleDir function returns incorrect result

### ISSUE THREAD

**Issue by aaronlehmann** [openllb/hlb#332]
This line of code appears to be wrong: https://github.com/openllb/hlb/blob/12055ea32a30db84c267c4d355ef198c2e2080fb/codegen/context.go#L76

`mod.Directory.Path()` is hardcoded to `.` by `parser.Parse`. Normally this `strings.TrimPrefix` does nothing, but if the filename is `./foo.hlb`, `strings.TrimPrefix` will remove the `.`, and `ModuleDir` will return `/`. This will make a `"download "./build"` get an error like:

```
ERROR: rpc error: code = Unknown desc = failed to create synctarget dest dir /build: mkdir /build: permission denied
```

I haven't been able to reproduce this with the `hlb` CLI, but passing in a filename starting with `./` into `command.Run` triggers this issue.

I'm not sure what this line of code is trying to accomplish. Should it just be removed, or is the correct fix something else?

**Comment by hinshun** [comment]
I think this is to trim the prefix for remote directories, and for local directories it's supposed to be a no-op.

**Comment by aaronlehmann** [comment]
> I think this is to trim the prefix for remote directories, and for local directories it's supposed to be a no-op.

Would this give us a reasonable `localPath` path for a `download` included in a remote module?

**Comment by aaronlehmann** [comment]
@hinshun: Happy to work on a fix for this issue if you can point me in the right direction.

**Comment by hinshun** [comment]
@aaronlehmann So there is no reproduction with just `hlb`?

I think was relying on the no-op behaviour, perhaps we should make that more explicit. We have to ensure fixing this doesn't break the different remote module edge cases (like remote module importing `./rel-path` within its remote fs, and remote module importing another remote module).

**Comment by aaronlehmann** [comment]
That's correct. I can't reproduce it with the HLB CLI.

By explicit, do you mean that we'd trip a prefix for remote directories, but not for local directories?

**Comment by hinshun** [comment]
Maybe only functions like export artifacts is always relative to user's cwd. But I wish we can make it clearer... In some of my notes, I had hoped functions like `download` are in an namespace like `local.download` which will make me happier.

**Comment by aaronlehmann** [comment]
Maybe the cleanest solution here is for `parser.Parse` to set the local directory `Path` to "" instead of ".". The "." looks arbitrary, and isn't actually a prefix we want to strip off.
