### ISSUE TITLE
support doublestar syntax for includePatterns and excludePatterns

### ISSUE THREAD

**Issue by coryb** [openllb/hlb#42]
Use case:  I want to import only .go files from a build tree to run `go build`.  

Suggestion:
```
include "." with option {
  includePatterns "**/*.go"
}
```
that would include all files in the current directory and down that match `*.go`.   I don't think llb supports this directly but I think can emulate it fairly efficiently in hlb.

Currently, if I wanted to implement something like this I think it would have to be:
```
include "." with option {
  includePatterns "*.go" "*/*.go" "*/*/*.go" "*/*/*/*.go" "*/*/*/*/*.go" "*/*/*/*/*/*.go" "*/*/*/*/*/*/*.go" "*/*/*/*/*/*/*/*.go" "*/*/*/*/*/*/*/*/*.go"
}
```

**Comment by hinshun** [comment]
@coryb How do you propose we emulate it in HLB? Generate single-asterisk wildcards from double-asterisk wildcards?

**Comment by coryb** [comment]
I had thought we would be able to just set `IncludePatterns` to an explicit list of files when we detect `**`, but some changes would be necessary to pass the local context path into the options where we process `option::local`. 

I looked into what it would take to add support to buildkit directly, it is confusing.  It appears buildkit uses `github.com/tonistiigi/fsutil` which then uses `github.com/moby/moby/pkg/fileutils` which does seem to support doublestar, but I think these support is dropped via the usage in fsutil.
