### ISSUE TITLE
How to use option::run secret?

### ISSUE THREAD

**Issue by coryb** [openllb/hlb#43]
From the run example:
https://openllb.github.io/hlb/reference/#fs-fs-runstring-arg

It appears like I should be able to do:
```
fs default() {
  image "busybox:latest"
  dir "/dir"
  run "ls" with option {
    secret "./tests" "/dir"
  }
```
The usage is:
```
option::run secret(string localPath, string mountPoint)
```

but there is no local context associated with this function, so I am not sure where it would be loading `localPath` from.  The error message implies that the first argument is some label but I am unclear how to set this up:
```
$ ./hlb run --log-output plain ./tests/bug.hlb
#1 compiling ./tests/bug.hlb
#1 DONE 0.0s

#2 docker-image://docker.io/library/busybox:latest
#2 resolve docker.io/library/busybox:latest
#2 resolve docker.io/library/busybox:latest 1.1s done
#2 CACHED

#3 ls
#3 ERROR: secret ./tests not found: not found
```

**Comment by hinshun** [comment]
@coryb I think this is a bug actually. Secrets must have a corresponding key in the solve just like how `local` and `ssh` do. HLB will need to plumb it somehow.

**Comment by coryb** [comment]
I am guessing that `secret` should be similar to `local`, in that we hash the input to generate an ID, then provide that ID to LLB?  Should it also be an `fs`?  Given how it is used in the `buildctl` command, it looks simlar in usage to `--local`.   I am thinking something like:

```
fs build(fs src, fs secrets) {
  image "busybox:latest"
  dir "/src"
  run "build" with option {
    mount src "/src"
    mount secrets "/secrets"
  }
}

fs default() {
  build fs {
    local "."
  } fs {
    secret "."
  }
}
```

Not sure if you think that is possible, or if you have other ideas?

**Comment by coryb** [comment]
Opened #PR44 for this. I tried the quasi-flesystem route, but that didnt pan out, so just fixed the `secret input target` usage to plumb it through.

**Comment by hinshun** [comment]
@coryb Yeah I think supporting it a generic `fs` will be difficult, since it needs to be supported in contexts outside of `run`. Unless we can figure out a clever hack, we need to stay close to LLB's implementation.
