### ISSUE TITLE
Unit test bundle for scope and identifiers

### ISSUE THREAD

**Issue by hinshun** [openllb/hlb#86]
Tests should go into `compile_test.go`, and the input program should be minimal as possible. There may be more than one test case per bullet point.

- [x] Function with duplicate names should produce error (functions, aliases).
- [x] Export name should exist in module scope.
- [x] Function with duplicate fields in the signature should produce error.
- [x] Calling selector that does not exist should produce error.
- [x] Calling selector on name that isn't an import should produce error.

**Comment by antonio-osorio** [comment]
@hinshun I would like to move `import` testing out of this ticket. The way that it is implemented right now it communicates with the buildkit client even for local files so the testing is a bit more involved.

**Comment by hinshun** [comment]
@antonio-osorio You're right, we should of moved it over in the first place, sorry. I think the `compile_test.go` really should be just testing the output of `checker.Check` and not the full `Compile`. I moved `compile_test.go` to `checker/checker_test.go` and simplified the test. I added an `import` test there, could you please port your test cases over this: #96
